name: "java-ms"
on:
  push:
    branches: ["main"]

jobs:
  build-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: actions/checkout@main
      - name: "print"
        run: |
          echo "successful ci job"
